# Generated by Django 4.2.13 on 2026-06-21 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('excerpt', models.TextField(max_length=400)),
                ('body', models.TextField()),
                ('cover_emoji', models.CharField(default='📰', max_length=10)),
                ('author_name', models.CharField(default='YoungRoots Team', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
