# Generated by Django 4.2.13 on 2026-06-21 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('contraception', 'Contraception'), ('rights', 'Rights'), ('gbv', 'GBV'), ('hiv', 'HIV / STIs'), ('consent', 'Consent'), ('mental_health', 'Mental Health'), ('pregnancy', 'Pregnancy'), ('relationships', 'Relationships')], max_length=30)),
                ('body', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
